services:
    frontend:
        build: ./tiqet-frontend
        depends_on:
            - backend
        ports:
            - 3000:3000

    backend:
        build: ./tiqet-backend
        depends_on:
            db:
                condition: service_healthy
        ports:
            - 8080:8080
        environment:
            - FRONTEND_URL=http://localhost:3000
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=tiqet
            - POSTGRES_PASSWORD=ILoveTiqet!
            - POSTGRES_DB=tiqet
        env_file: ".env.backend"

    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=tiqet
            - POSTGRES_USER=tiqet
            - POSTGRES_PASSWORD=ILoveTiqet!
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U tiqet -d tiqet"]
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        env_file:
            - .env.backend